"""add value to predict

Revision ID: a900e1b90d4e
Revises: a4ba6502ed21
Create Date: 2021-03-09 21:10:36.003191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a900e1b90d4e'
down_revision = 'a4ba6502ed21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('predict_value', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict', 'predict_value')
    # ### end Alembic commands ###
