"""add new column for user activate

Revision ID: b5f29fbc6a74
Revises: 5036695ebc4d
Create Date: 2019-03-02 19:35:10.837305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f29fbc6a74'
down_revision = '5036695ebc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

# 这是sqlite 尽量避免downgrade 会报错 不知为何，mysql就不会报错
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_activated')
    # ### end Alembic commands ###
