"""add img to Tweet

Revision ID: e48ebc1ff51c
Revises: b5f29fbc6a74
Create Date: 2021-03-09 15:35:43.040683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48ebc1ff51c'
down_revision = 'b5f29fbc6a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'img')
    # ### end Alembic commands ###
